### ISSUE TITLE
Validate TSV column contents using schema.objects.columns type and format information

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#1607]
Example rule:

`ASLCONTEXT_TSV_INCONSISTENT`: `In the 'sub-<label>[_ses-<label>][_acq-<label>][_rec-<label>][_run-<index>]_aslcontext.tsv', the 'volume_type' can only be filled with volumes ['cbf' ,'m0scan', 'label', 'control', 'deltam'].`

From [objects.columns](https://github.com/bids-standard/bids-specification/blob/eb658db44deade3ef3eb0ffaa192bb5b77d78de0/src/schema/objects/columns.yaml#L775-L787):

```YAML
volume_type:
  name: volume_type
  display_name: ASL volume type
  description: |
    The `*_aslcontext.tsv` table consists of a single column of labels identifying
    the `volume_type` of each volume in the corresponding `*_asl.nii[.gz]` file.
  type: string
  enum:
    - control
    - label
    - m0scan
    - deltam
    - cbf
```
