### ISSUE TITLE
Validation of consistency between timeframes in metadata and imaging data for PET

### ISSUE THREAD

**Issue by mnoergaard** [bids-standard/legacy-validator#2097]
We have experienced a few cases (most recently the Dallas Lifespan Brain Study on OpenNeuro, https://openneuro.org/datasets/ds004856) where there seem to be inconsistencies between the metadata timing information (e.g. FrameDuration) and the number of timeframes present in the PET data (4th dimension). For example, sub-1003_ses-wave1_trc-18FAV45_run-1_pet.json has two entries for the FrameDuration tag suggesting that two frames should be present in the PET data. However, when inspecting the PET data, the data is only 3D suggesting just a single frame. 

Would it be possible to introduce a validation step that checks for this?

**Comment by effigies** [comment]
The best way to do this would be to add a schema check. An example would be [rules.checks.dwi.DWIVolumeCount](https://github.com/bids-standard/bids-specification/blob/0de4c9c11c72676033a466b320e8a00f5890724e/src/schema/rules/checks/dwi.yaml#L4-L18):

```yaml
DWIVolumeCount:
  issue:
    code: VOLUME_COUNT_MISMATCH
    message: |
      The number of volumes in this scan does not match the number of volumes in the
      associated '.bvec' and '.bval' files.
    level: error
  selectors:
    - intersects([suffix], ["dwi", "epi"])
    - '"bval" in associations'
    - '"bvec" in associations'
    - type(nifti_header) != "null"
  checks:
    - associations.bval.n_cols == nifti_header.dim[4]
    - associations.bvec.n_cols == nifti_header.dim[4]
```

You could add a `pet.yaml` file to the checks directory (https://github.com/bids-standard/bids-specification/tree/master/src/schema/rules/checks) with something on the order of:

```yaml
PETFrameConsistency:
  issue:
    code: PET_FRAME_CONSISTENCY
    message: |
      [Write a helpful message]
    level: error
  selectors:
    - suffix == 'pet'
    - type(nifti_header) != "null"
    - sidecar.FrameDuration
  checks:
    - length(sidecar.FrameDuration) == nifti_header.dim[4]
```

See https://bidsschematools.readthedocs.io/en/latest/description.html#checks for more on writing checks.
